### PR TITLE
Remove stale netty configuration

### PR DESCRIPTION
**Pull request by raboof**
#59

### CODE REVIEW

**Comment by johanandren** [comment]
Did you get this to work locally? (I had problems)

**Review by patriknw — APPROVED** [review]
LGTM, Artery is enabled by default so this shouldn't be used. Do we have any references to port 2552 in deployment spec? Artery is using a different default.

**Comment by johanandren** [comment]
I think it is referenced in the deployment config for k8

**Comment by raboof** [comment]
> Did you get this to work locally? (I had problems)

I didn't try (seemed like a safe change and travis has good coverage here)

What kind of problems did you see?

**Comment by raboof** [comment]
> Do we have any references to port 2552 in deployment spec?

Hmm, we do. I'll look a bit closer.

**Comment by johanandren** [comment]
I couldn't get it to run, but I also had weird minikube problems so didn't figure out if it was that or if the deployment was incorrect.

**Comment by patriknw** [comment]
I think @chbatey removed it from deploy spec in other example (deployment guide).

**Comment by raboof** [comment]
It comes up for me with the expected actor path and port, e.g.:

> Received InitJoinAck message from [Actor[akka://ClusterApp@172.18.0.2:25520/system/cluster/core/daemon#-1547336343]]

Indeed it's confusing 2552 is exposed in `kubernetes/akka-cluster.yml`, I'll remove those references

**Review by johanandren — APPROVED** [review]
LGTM, thanks @raboof

**Pull request merged**
