### PR TITLE
add example for k8s DNS in Java, sorry still SBT, no cluster singleton

### PR DESCRIPTION
**Pull request by michael-read**
I was working in the akka-management project, which relies on the main build.sbt, so it won't build without that dependency structure.

### CODE REVIEW

**Comment by patriknw** [comment]
@michael-read sorry if reviews of fell between the cracks. I'll ask @chbatey and @raboof to take a look.

**Review by raboof — APPROVED** [review]
I made sure the project can be built standalone and tested in travis, :+1:, thanks a lot for the contribution @michael-read !

**Review by chbatey — APPROVED** [review]
LGTM

**Review by chbatey — APPROVED** [review]
LGTM

**Pull request merged**
